# Project info
site_name: nGenue
site_description: Ngenue documentation portal
site_author: Dipender Sharma
site_url: https://ngenue.com

# Repository
# repo_name: 'nGenue'
# repo_url: ''
# edit_uri: ''

# Copyright
copyright: Copyright &copy; 2024 nGenue

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/ngenue_logo.jpeg
  favicon: assets/images/ngenue_logo.jpeg
  icon:
    repo: fontawesome/brands/github
  palette:
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
  font:
      text: Noto Sans
      code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - toc.follow
    - announce.dismiss
    # - content.tabs.link
    # - content.tooltips
    # - search.highlight
    - navigation.sections
    - navigation.footer
    # - content.action.edit
    # - content.action.view
    - content.code.annotate


extra:
  homepage: https://ngenue.com
  generator: true
  analytics:
    provider: google
    property: G-DVHHGW7W9R
    feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >- 
                Thanks for your feedback! Help us improve this page by
                <a href="" target="_blank" rel="noopener">filing an issue</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ngenue
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/ngenue
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ngenue
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ngenue

extra_css:
  - assets/css/custom.css
  - assets/css/puml.css
extra_javascript:
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/typewriter.js
  - https://unpkg.com/typewriter-effect@latest/dist/core.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  # - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     user: hummingbot
  #     repo: hummingbot
  #     repo_url_shorthand: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - tables

plugins:
  - include-markdown
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: false
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

  
  # - git-authors

  # - git-committers:
      repository: sarahjones123/nGenue_docs
      branch: main
      
  # - git-revision-date-localized:
      enable_creation_date: true
      

# Navigation
nav:
  - Home: index.md

  - Documentation: 
    - Getting started with nGenue: 
      - getting_started/index.md
      # - nGenue overview: home.md
      - Key features and benefits: features.md
      - System requirements: system_requirements.md
      - Installation and initial setup: installation.md

    - ETRM:
      - etrm/index.md
      - Deal management: 
        - Overview: deal_management/overview.md
        - Create a deal:
          - Physical deal: deal_management/physical_deal.md
          - Physical retail deal: deal_management/physical_retail_deal.md
          - Swap deal: deal_management/swap_deal.md
          - Future deal: deal_management/future_deal.md
          - Physical NG deal: deal_management/ng_deal.md
          - Production deal: deal_management/production_deal.md
          - Cash deal: deal_management/cash_deal.md
          - Physical wellhead deal: deal_management/wellhead_deal.md
        - Swap deal blotter: Swap deal blotter
        - Futures deal blotter: Futures deal blotter
        - Evergreen deals process: Evergreen deals process
        - Deal activity log: Deal activity log
      - Pricing configurations: pricing/index.md 
      - Nominations: nominations
      - Settlements: settlements

    - User management: 
      - user_management/index.md
      - End users: 
          - Overview: user_management/end_users/overview.md
          - Configure: user_management/end_users/create_end_user.md
      - Counterparty:
          - Overview: user_management/counterparty/counterparty.md
          - Configure: user_management/counterparty/create_counterparty.md

    - System configuration:
      - system_configuration/index.md
      - Menu configuration: 
          - Overview: system_configuration/menu_configuration/overview.md
          - Configure: system_configuration/menu_configuration/configure.md
      - Global setting: 
          - Overview: system_configuration/global_settings/overview.md
          - Configure: system_configuration/global_settings/configure.md


    - How-to: 
      - how_to/index.md   

    - FAQs: 
      - faqs/index.md

    - Use cases:
      - use_cases/index.md

    - Troubleshootings: 
      - troubleshootings/index.md

    - Glossary: 
      - glossary/index.md

    - Template: 
      - template/index.md
      # - Markdown syntax: template/markdown_syntax_code.md

#  - Releases:
    - Releases: releases/index.md

#  - Academy:
    - Academy: academy/index.md
  
#  - Blog: 
    - blog/index.md
