# Project info
site_name: nGenue
site_description: Ngenue documentation portal
site_author: Dipender Sharma
site_url: https://ngenue.com

# Repository
# repo_name: 'nGenue'
# repo_url: ''
# edit_uri: ''

# Copyright
copyright: Copyright &copy; 2024 nGenue

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/ngenue_logo.jpeg
  favicon: assets/images/ngenue_logo.jpeg
  icon:
    repo: fontawesome/brands/github
  palette:
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
  font:
      text: Noto Sans
      code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - toc.follow
    - announce.dismiss
    # - content.tabs.link
    # - content.tooltips
    # - search.highlight
    - navigation.sections
    - navigation.footer
    # - content.action.edit
    # - content.action.view
    - content.code.annotate


extra:
  homepage: https://ngenue.com
  generator: true
  analytics:
    provider: google
    property: G-DVHHGW7W9R
    feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >- 
                Thanks for your feedback! Help us improve this page by
                <a href="" target="_blank" rel="noopener">filing an issue</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ngenue
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/ngenue
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ngenue
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ngenue

extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/typewriter.js
  - https://unpkg.com/typewriter-effect@latest/dist/core.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  # - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     user: hummingbot
  #     repo: hummingbot
  #     repo_url_shorthand: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - tables

plugins:
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: false
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      

# Navigation
nav:
  - Home: index.md

  - Docs: 
    - nGenue Overview: home.md
    - Key features: features.md
    - Benefits: advantages.md

    - Getting started: 
      - getting_started/index.md
      - End users: 
          - Overview: getting_started/end_users/overview.md
          - Configure: getting_started/end_users/create_end_user.md
      - Counterparty:
          - Overview: getting_started/counterparty/counterparty.md
          - Configure: getting_started/counterparty/create_counterparty.md

    - Authentication:
      - authentication/index.md
      - Sign up: authentication/sign_up.md
      - Sign in: authentication/sign_in.md
      - Forgot password: authentication/forgot_password.md

    - How-to: 
      - how_to/index.md   

    - FAQs: 
      - faqs/index.md

    - Use Cases:
      - use_cases/index.md

    - Troubleshootings: 
      - troubleshootings/index.md

    - Glossary: 
      - glossary/index.md

    - Template: 
      - template/index.md
      # - Markdown syntax: template/markdown_syntax_code.md

  - Releases:
    - Releases: releases/index.md

  - Academy:
    - Academy: academy/index.md
  
  - Blog: 
    - blog/index.md
